language: python
sudo: required
dist: trusty

before_install:
- sudo apt-get update -qq

install:
- sudo util/install.sh -fnvw

script:
- sudo mn --test pingall
- sudo python mininet/test/runner.py -v -quick
- sudo python examples/test/runner.py -v -quick

notifications:
  email:
    on_success: never
# More details: https://docs.travis-ci.com/user/notifications#Configuring-email-notifications
